### ISSUE TITLE
Show only first line of the commit message

### ISSUE THREAD

**Issue by jenncoop** [steamclock/coda-changelog#46]
We do squash merges on many of our repos, so we end up with the full commit history of the PR in the commit message. Let's try to grab just the first line instead of posting the whole thing to Coda.

![Screen Shot 2021-12-07 at 8.38.52 AM.png](https://images.zenhubusercontent.com/55f320f14f7a08fbb7f4d8e0/e1bf7533-8721-47ae-971c-be521dba718b)

**Comment by AZielinsky95** [comment]
Hmm so I'd split the message by a double line break and that would work, however, we run the risk of losing important commit info. For instance, the first row in your screenshot would chop off that second point, which might be an important detail. 

I could look for a '*' character that indicates a squashed commit message and remove those? Let me know what you think

**Comment by jenncoop** [comment]
Yeah let's try looking for `*` and remove those lines and see how that works 👍
